### ISSUE TITLE
#V1.0 Buchungen nach Kontolöschung noch vorhanden

### ISSUE THREAD

**Issue by tbspace** [Marcel9494/Haushaltsbuch#14]
Nachdem man ein Konto gelöscht hat, sind die damit verknüpften Buchungen noch immer vorhanden. 
Ggf. bei Kontolöschung fragen, ob verknüpfte Buchungen ebenfalls gelöscht werden sollen oder direkt mit löschen. Andernfalls laufen die Buchungen ins Leere.

**Comment by Marcel9494** [comment]
Folgender Ablauf muss implementiert werden:
1. Konto löschen Dialog wird geöffnet mit Auswahl Ja oder Nein
2. Bei Nein wird Dialog wieder geschlossen und nichts weiter passiert.
3. Bei Ja wird folgendes der Reihe nach geprüft:
    3.1 Ist noch Geld auf dem Konto das gelöscht werden soll vorhanden?
    3.2 Wenn Nein (amount = 0) Konto löschen
    3.3 Wenn Ja Geld an anderes Konto übertragen => Konto muss angegeben werden wohin das Geld überwiesen werden soll
    3.4 Sobald das Geld überwiesen wurde => Konto löschen
4. Wenn eine Buchung bearbeitet wird muss geprüft werden, ob das/die angegebene(n) Konto(en) noch vorhanden sind, wenn ein Konto nicht mehr vorhanden ist muss dies dem Benutzer in der GUI angezeigt werden und er muss ein anderes Konto auswählen. Ansonsten kann die Buchung nicht bearbeitet werden, weil sonst die Buchung ins Leere laufen würde und die Kontostände nicht mehr übereinstimmen würden.
