### ISSUE TITLE
Gradle Fehlermeldung beim Starten der App nach dem Clonen im Simulator und während des Builds

### ISSUE THREAD

**Issue by tbspace** [Marcel9494/Haushaltsbuch#3]
Fehlermeldung:

![image](https://github.com/Marcel9494/Haushaltsbuch/assets/49919542/d7c3d480-71bb-4a7f-b09b-def14d8779ac)

Textform:
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/blockt/Dokumente/01_Coding/07_AndoidApps/01_AppDevOp/Haushaltsbuch/android/settings.gradle' (/home/blockt/.gradle/caches/7.0.2/scripts/bt53u1oym6apy0m101vnrgrbi).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by tbspace** [comment]
Ich habe selbst ein wenig ausprobiert. Angeblich liegt das bei mir daran, dass ich Java 17 habe und in deinem Verzeichnis sich der Verweis auf Gradle 7.0.3 befindet. Die beiden Versionen sind nicht kompatible.

- Lösungsversuch 1: Downgrade von Java-17 zu Java-11 => Hat nicht funktioniert. Ich konnte 11 installieren und die Projekteinstellungen auch darauf verweisen, aber es wurde scheinbar doch 17 genommen

- Lösungsversuch 2: Update von Gradle auf eine mit Java-17 kompatible Version (7.5) => Hat funktioniert. Dazu musste ich in zwei Dateien im Ordner "android" Einstellungen ändern.

Vielleicht kannst du auch auf eine neuere Gradle Version wechseln? Das würde zumindest die Zusammenarbeit erleichtern. Sollte ich nämlich jetzt etwas ändern und einen Commit machen, würde ich auch diese Android/Gradle Einstellungen Commiten und du ggf. runterladen.

**Comment by Marcel9494** [comment]
Ich habe jetzt auch auf eine neue Gradle Version geupdatet und dabei folgende Änderungen gemacht:

1. Unter android --> build.gradle von 7.0.2 auf 7.4.2 geupdatet dabei wurde folgende Zeile geändert:
`classpath 'com.android.tools.build:gradle:7.4.2'`
2. Unter android --> gradle --> wrapper --> gradle-wrapper.properties von 7.0.2-all.zip auf 7.5.1-all.zip geupdatet dabei wurde die distributionUrl geändert:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip`
3. Gradle JDK Version von 11 auf 17.0.7 geupdatet (Amazon Corretto)
![grafik](https://github.com/Marcel9494/Haushaltsbuch/assets/93829086/a19d429d-6807-41a6-984d-07d0a23680ce)

Änderungen wurde mit folgendem Commit gepusht:
https://github.com/Marcel9494/Haushaltsbuch/commit/de8eb30638d172c03fb90722321494c57f1574c3

Nun sollten wir dort keine Probleme mehr haben wäre gut wenn du das noch bei dir testen könntest, ob es mit diesen neuen Einstellungen bei dir ohne Probleme funktioniert.

**Anmerkungen:**
Alle Gradle Releases können unter folgendem Link nachgeschaut werden: https://gradle.org/releases/
Alle Maven Releases können hier nachgeschaut werden: https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google

**Comment by tbspace** [comment]
Ich habe deine Versionen in den Settings getestet. Bei mir läuft auch alles ohne Probleme!

**Comment by Marcel9494** [comment]
Sehr gut perfekt 👍
