### ISSUE TITLE
#V1.0 Einzelne Kontenänderungen bei Serienbuchungen

### ISSUE THREAD

**Issue by tbspace** [Marcel9494/Haushaltsbuch#33]
Bei einer Serienbuchung lassen sich bei einzelne Einträgen die Konten nicht mehr ändern. Bsp. bei einer monatlichen Serienbuchung wird nur an einem Monat der Betrag nicht überwiesen, sondern Bar bezahlt.

**Comment by Marcel9494** [comment]
Habe gerade mal folgenden Fall getestet:
1. Ich habe eine Serienbuchung erstellt die alle vom Girokonto abgebucht werden.
2. Anschließend habe ich eine Buchung der Serie ausgewählt und das Konto vom Girokonto auf das Verrechnungskonto geändert das hat bei mir funktioniert und wurde dann auch vom richtigen Konto abgebucht (vom Verrechnungskonto).
Habe ich den Fehler falsch verstanden?

**Comment by Marcel9494** [comment]
Dieser Fall wurde gerade nochmals getestet und bei einer Änderung des Kontos bei einer Serienbuchung wurde der Betrag vom neuen Konto richtig abgezogen und beim alten Konto richtig hinzugefügt.
=> Bug wird geschlossen. Feature funktioniert.
