### ISSUE TITLE
#V1.0 Bei unterschiedlichen Gerätetypen taucht der Pixeloverflow Bug auf

### ISSUE THREAD

**Issue by tbspace** [Marcel9494/Haushaltsbuch#38]
In der aktuellen Version erhalte ich bei meinem Galaxy S10 erneut den Pixel Overflow Fehler, sobald ich das BottomSheet für die Betragseingabe öffne.
Mögliche Lösung für unterschiedliche Displaygrößen: Auslesen des verfügbaren Platzes oder des benötigten Platzes eines Child Widgets mittels MediaQuery und somit eine dynamische Anpassung der Widgetgrößen => genaue Umsetzung noch nicht ganz verstanden

**Comment by Marcel9494** [comment]
Ja, das ist eine gute Idee mit den dynamischen Größen über MediaQuerys.
